### ISSUE TITLE
uninitialized constant WillPaginate::ActionView / undefined local variable or method `can_view_jenkins_jobs'

### ISSUE THREAD

**Issue by mrueg** [jbox-web/redmine_jenkins#10]
Clicking on projects/project_id/jenkins in a freshly started redmine instance results in

```
ActionController::RoutingError (uninitialized constant WillPaginate::ActionView):
```

Clicking a second time on projects/project_id/jenkins results in Error 500.

```
NameError (undefined local variable or method `can_view_jenkins_jobs' for #<JenkinsController:0x007f4b01117d50>):
```

redmine-2.4.6
will_paginate-3.0.7
jenkins_api_client-1.0.1

**Comment by mrueg** [comment]
With latest git commit, i get this:

```
Started GET "/projects/project1/jenkins" for ip-address at 2014-09-14 03:40:29 +0200
Processing by JenkinsController#index as HTML
  Parameters: {"project_id"=>"project1"}
  Current user: user1 (id=1)
  Rendered common/error.html.erb within layouts/base (0.2ms)
Filter chain halted as :find_project rendered or redirected
Completed 404 Not Found in 29.4ms (Views: 21.4ms | ActiveRecord: 1.3ms)
```

**Comment by canatella** [comment]
It seems to be working for me if I add 

require 'will_paginate/view_helpers/action_view.rb'

in

plugins/redmine_jenkins/app/helpers/will_paginate_helper.rb

**Comment by mrueg** [comment]
That seems to fix it for me, too. @n-rodriguez can you add this to the repository?
