### ISSUE TITLE
Do not modify migrations that are already on github

### ISSUE THREAD

**Issue by akaias** [jbox-web/redmine_jenkins#14]
Hi there,

i installed the first version of the plugin, 
now i updated the code and i ran the migrations.

BUT

since you CHANGED the migrations that have been in the repository , they where not executed again.
so i basically had to migrate them back to version 0 and redo it resulting in a loss of data.

Please, once a migration is pushed to github DO NOT MODIFY it.
create a new one.

Cheers

Axel

**Comment by n-rodriguez** [comment]
Since the plugin is still in development (there is no version called 1.0) this is not an issue.
