### ISSUE TITLE
conflicts with gem

### ISSUE THREAD

**Issue by vanadar** [jbox-web/redmine_jenkins#15]
i can't install the latest patch on redmine 2.5.2: i have a confilct when doing "bundle install"  : 

You cannot specify the same gem twice with different version requirements.
You specified: rspec (~> 2.0) and rspec (~> 3.0.0) 

it looks like i can't install redmine_jenkins AND redmine_dashboard

**Comment by n-rodriguez** [comment]
Thanks for your feedback!
