### ISSUE TITLE
shoulda conflict

### ISSUE THREAD

**Issue by ndarilek** [jbox-web/redmine_jenkins#17]
Getting the following error:

```
Sep 25 20:51:05 thewordnerd.info docker[9123]: You specified: shoulda (~> 3.3.2) and shoulda (~> 3.5.0)
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/plugins/redmine_jenkins/Gemfile:11:in `block (2 levels) in eval_gemfile'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/plugins/redmine_jenkins/Gemfile:7:in `block in eval_gemfile'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/Gemfile:106:in `instance_eval'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/Gemfile:106:in `block in eval_gemfile'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/Gemfile:103:in `glob'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/Gemfile:103:in `eval_gemfile'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/config/boot.rb:6:in `<top (required)>'
Sep 25 20:51:05 thewordnerd.info docker[9123]: /usr/src/app/config/application.rb:1:in `<top (required)>'
...
```

This is under Redmine 2.5.2. I ran "bundle install --without test development" when installing Redmine. Seems like I shouldn't need shoulda to run in production. I did run another "bundle install --without test development" before restarting Redmine so I don't know what I have to do to not install this test dependency when launching.

Thanks.

**Comment by n-rodriguez** [comment]
> so I don't know what I have to do to not install this test dependency when launching.

I don't think this dependency is really installed. Check it with a `bundle list`.
But in order to build his dependency tree, `bundle` analyzes all groups in Gemfile(s) and halt on conflicts. To avoid the error, you can safely comment the line.
