### ISSUE TITLE
Changelog should be collapsible

### ISSUE THREAD

**Issue by evfool** [jbox-web/redmine_jenkins#21]
We have only four builds set up in Redmine Jenkins, but some of them have very long changelogs, and to get to the last job we have to scroll a lot.

It would be nice if the changelog would be a collapsible pane, showing only the top 4-5 rows of the changelog and a "more" button to expand the changelog for the given build.

**Comment by n-rodriguez** [comment]
Done!
Thank you!

**Comment by evfool** [comment]
Great news, thanks for your work, it's greatly appreciated.
