### ISSUE TITLE
View console log in same tab issue

### ISSUE THREAD

**Issue by evfool** [jbox-web/redmine_jenkins#22]
Currently when clicking the status link of a build (with tooltip See console output) I only get a big white screen with a blue OK button in the lower right corner. This only happens when simply left-clicking to open in the same window. Opening in a new tab shows the console output correctly.

**Comment by n-rodriguez** [comment]
> I only get a big white screen with a blue OK button in the lower right corner

Are you sure it's a big white screen?
Scroll a bit and you'll find Jenkins output (which can be pretty big) ;)

**Comment by evfool** [comment]
Ok, found that. It's not empty, but contains one very long line, which causes the div with the <pre> containing the log output to span to a larged width than the size of the screen, and there is no horizontal scrollbar, so I only see content when I am at the long line. 
When clicking on "Inspect element" from firefox however the thing is scrolled to the start of the line, so everything gets visible.
Anyway, I guess the key to finding this was the long line, I hope with this (a jenkins log with one very long line) you will be able to reproduce the problem. Feel free to ask anything, I'll be happy to provide further input for fixing this.
