### ISSUE TITLE
nil values produce errors: app/views/jenkins_jobs/_job_solo.html.erb

### ISSUE THREAD

**Issue by leonisCacheFlo** [jbox-web/redmine_jenkins#6]
It seems that some line in app/views/jenkins_jobs/_job_solo.html.erb are not nil-safe which results in 500 errors.

It happens after I activated the module for a redmine project and connected (successfully) to my jenkins instances, which has not run any jobs yet, but exactly one defined.

The following lines were producing problems, if there were no jobs yet.

```
  37: <%= Time.at(job.latest_build_duration/1000).strftime "%M:%S" %>
```

Rambo-bugfixing:

```
  37: <%= Time.at(job.latest_build_duration/1000).strftime "%M:%S"  rescue "00:00" %>
```

And:

```
40: <% latest_changesets = job.jenkins_builds.first.jenkins_build_changesets %>
```

And again, rescuing helps the dorky way:

```
 <% latest_changesets = job.jenkins_builds.first.jenkins_build_changesets rescue [] %>
```

Is there something I forgot to do before or is that still an open issue?
Cheers, Florian

**Comment by thomasli-x** [comment]
Hi, leonisCacheFlo. I met the same problem.... THANK YOU VERY MUCH! it works!

**Comment by n-rodriguez** [comment]
Hi there! Thanks for your feedback! (and sorry for the delay)

This is now fixed : https://github.com/jbox-web/redmine_jenkins/commit/5820e4e28f23d8a2f1473c98b923afa4d428c9a8
