### ISSUE TITLE
Redmine 3.4.x

### ISSUE THREAD

**Issue by jhyry-gcpud** [jbox-web/redmine_jenkins#61]
Is this plugin going to be updated for 3.4.x?
Or is it already compatible?

**Comment by macintoshplus** [comment]
I use with Redmine 3.4 without error.

**Comment by sabyasachimondal** [comment]
Dear macintoshplus,

I am facing problem for installing this plugin into Redmine 3.4.5 . I have installed it from Bitnami and the platform is windows. Can you please help?

**Comment by macintoshplus** [comment]
Sorry,

I use this version: https://github.com/InExtenso/redmine_jenkins/commits/devel
